// ✏️ 网站文案（保存于 2026-08-15）
window.COPY_V = "2026-08-15-a";
window.COPY = {
  "tab.about": "关于我",
  "tab.academic": "学术经历",
  "tab.work": "实践经历",
  "tab.moments": "人生瞬间",
  "hero.lead": "<strong>Hi 你好，我是珮伊</strong>",
  "hero.p1": "一个穿梭于人文和科技之间的探索者<br>永远不会放弃的事情是和真实的人产生连接，以及对美的追求",
  "tag.about.1": "教育经历",
  "tag.about.1.en": "EDUCATION",
  "tag.about.2": "循环播放中",
  "tag.about.2.en": "On Repeat",
  "tag.about.4": "最佳现场",
  "tag.about.4.en": "Best Live/SHOW",
  "hint.vinyl": "（横滑拖动 点击可跳转播放器）",
  "hint.drama.pre": "已观看",
  "hint.drama.post": "部现场作品",
  "hint.drama.sub": "以下15部为个人给出的五星佳作",
  "tag.academic.1": "研究兴趣",
  "tag.academic.1.en": "Research Interests",
  "tag.academic.2": "论文与会议",
  "tag.academic.2.en": "Publications",
  "tag.academic.3": "本科毕业论文",
  "tag.academic.3.en": "Thesis",
  "tag.academic.4": "课题项目",
  "tag.academic.4.en": "Projects",
  "tag.work.1": "实习与工作",
  "tag.work.1.en": "Experience",
  "tag.work.2": "项目与作品",
  "tag.work.2.en": "PROJECTS",
  "tag.moments.1": "人生瞬间",
  "tag.moments.1.en": "Moments",
  "footer.left": "© 2026 赵珮伊 Peiyi Zhao",
};
